version: '3'
services:
  main:
     build: 
        context: ./server-client
     environment:
        OTHER : "http://backend:3000/" 
     ports: 
        - "4000:4000"

  backend:
     environment:
        PORTZ: 3000
     build: 
        context: ./server

     
